language: csharp
solution: typon.sln
install:
  - nuget restore typon.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release typon.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./typon.Tests/bin/Release/typon.Tests.dll
