language: csharp
script:
  - xbuild /p:Configuration=Release typon.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore typon.sln
after_script:
  - nunit-console typon.Tests/bin/Release/Tests.dll
